/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ipc1_proyecto1_202300668.interfaz;

import ipc1_proyecto1_202300668.IPC1_Proyecto1_202300668;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author jmfuente
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        
        setLocationRelativeTo(null);
        setResizable(false);
        
        //---------Crear tabla------------
        String[] columnsName = {"Código", "Nombre", "Genero", "Contraseña"};
        
        /*
        Object[][] data ={
            {"001", "Juan", "M", "123"}
        };*/
        
        JTable table_estudiante = new JTable (IPC1_Proyecto1_202300668.mostrarInvestigadores(), columnsName);
        
        JScrollPane scrallPaneTable = new JScrollPane(table_estudiante);
        
        scrallPaneTable.setBounds(25, 45, 550, 300);
        
        panelInvestigador.add(scrallPaneTable);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelInvestigador = new javax.swing.JPanel();
        btnCrearInvestigador = new javax.swing.JButton();
        btnEliminarInvestigador = new javax.swing.JButton();
        btnCargarInvestigador = new javax.swing.JButton();
        btnActualizarInvestigador = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearInvestigador.setBackground(new java.awt.Color(255, 230, 189));
        btnCrearInvestigador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCrearInvestigador.setText("Crear");
        btnCrearInvestigador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCrearInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearInvestigadorActionPerformed(evt);
            }
        });

        btnEliminarInvestigador.setBackground(new java.awt.Color(255, 230, 189));
        btnEliminarInvestigador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarInvestigador.setText("Eliminar");
        btnEliminarInvestigador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInvestigadorActionPerformed(evt);
            }
        });

        btnCargarInvestigador.setBackground(new java.awt.Color(255, 230, 189));
        btnCargarInvestigador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCargarInvestigador.setText("Cargar");
        btnCargarInvestigador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCargarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarInvestigadorActionPerformed(evt);
            }
        });

        btnActualizarInvestigador.setBackground(new java.awt.Color(255, 230, 189));
        btnActualizarInvestigador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarInvestigador.setText("Actualizar");
        btnActualizarInvestigador.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizarInvestigador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarInvestigadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInvestigadorLayout = new javax.swing.GroupLayout(panelInvestigador);
        panelInvestigador.setLayout(panelInvestigadorLayout);
        panelInvestigadorLayout.setHorizontalGroup(
            panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvestigadorLayout.createSequentialGroup()
                .addContainerGap(636, Short.MAX_VALUE)
                .addGroup(panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelInvestigadorLayout.createSequentialGroup()
                        .addComponent(btnCargarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizarInvestigador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelInvestigadorLayout.createSequentialGroup()
                        .addComponent(btnCrearInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelInvestigadorLayout.setVerticalGroup(
            panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvestigadorLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarInvestigador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInvestigadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCargarInvestigador, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btnActualizarInvestigador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Investigadores", panelInvestigador);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearInvestigadorActionPerformed
        // TODO add your handling code here:
        
        FormularioInvestigador vtn_formInvestigador = new FormularioInvestigador();
        this.dispose();
    }//GEN-LAST:event_btnCrearInvestigadorActionPerformed

    private void btnEliminarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInvestigadorActionPerformed
        // TODO add your handling code here:
        
        EliminarInvestigador vtn_formInvestigador = new EliminarInvestigador();
        this.dispose();
    }//GEN-LAST:event_btnEliminarInvestigadorActionPerformed

    private void btnCargarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarInvestigadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarInvestigadorActionPerformed

    private void btnActualizarInvestigadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarInvestigadorActionPerformed
        // TODO add your handling code here:
        
        EditarInvestigador vtn_formInvestigador = new EditarInvestigador();
        this.dispose();
    }//GEN-LAST:event_btnActualizarInvestigadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarInvestigador;
    private javax.swing.JButton btnCargarInvestigador;
    private javax.swing.JButton btnCrearInvestigador;
    private javax.swing.JButton btnEliminarInvestigador;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelInvestigador;
    // End of variables declaration//GEN-END:variables
}
